# 資料庫連線設定
spring.datasource.url=jdbc:mysql://220.132.139.112:3306/google_places_test?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=teamuser1
spring.datasource.password=Foodmap123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 設定（視情況調整）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
